// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsA-Kt8G7cxIXq3DKkCmToHVZuzD9z3N0',
    appId: '1:523655112271:web:f122894a69b74be9bf2c3a',
    messagingSenderId: '523655112271',
    projectId: 'qbrix-cdfb1',
    authDomain: 'qbrix-cdfb1.firebaseapp.com',
    storageBucket: 'qbrix-cdfb1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByhfU_6jvjTVT89ODql-mqhGbRHzTa030',
    appId: '1:523655112271:android:5c953c9e39269be7bf2c3a',
    messagingSenderId: '523655112271',
    projectId: 'qbrix-cdfb1',
    storageBucket: 'qbrix-cdfb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFshGxwk1i368qChjrNb2CdFTCq9bOmto',
    appId: '1:523655112271:ios:a621709268afa1eabf2c3a',
    messagingSenderId: '523655112271',
    projectId: 'qbrix-cdfb1',
    storageBucket: 'qbrix-cdfb1.appspot.com',
    iosBundleId: 'com.example.obrix',
  );
}
